name: Bring Prod Hotfixes to Main

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      custom_branch_name:
        description: "Custom Branch Name (optional)"
        required: false
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Prod Branch
        uses: actions/checkout@v3
        with:
          ref: "prod"

      - name: Install jq (JSON Processor)
        run: sudo apt-get install jq

      - name: Get Application Version
        id: get_version
        run: |
          APP_VERSION=$(jq -r '.version' package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Determine Branch Name
        id: set_branch_name
        run: |
          if [ -z "${{ github.event.inputs.custom_branch_name }}" ]; then
            echo "BRANCH_NAME=prod-${{ env.APP_VERSION }}-to-main" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.event.inputs.custom_branch_name }}" >> $GITHUB_ENV
          fi

      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Main-Update Branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}

      - name: Merge Prod into Main-Update
        run: |
          git merge --no-ff origin/prod

      - name: Push to GitHub
        run: |
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        run: |
          gh pr create --base main --head ${{ env.BRANCH_NAME }} --title "Merge Prod hotfixes into Main (${{env.BRANCH_NAME}})" --body "Merging hotfixes from Prod into Main, branch ${{ env.BRANCH_NAME }}." --label "internal"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
